site_name: Preisthe's MkDocs Material Documentation
site_url: https://sitename.example
theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light
      primary: blue
      accent: deep orange

# code blocks
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences