site_name: Preisthe's Notebook
site_url: https://preisthe.github.io/Mkdocs-Notebook/
repo_name: preisthe/Mkdocs-Notebook
repo_url: https://github.com/preisthe/Mkdocs-Notebook
copyright: Copyright &copy; 2024 Preisthe

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon_1Js_icon.ico
  palette:
    # Dark Mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark
      primary: blue grey
      accent: cyan

    # Light Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Light
      primary: teal
      accent: green
  
  features:
    - navigation.footer
    - navigation.tabs

markdown_extensions:
  # code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # math
  - pymdownx.arithmatex:
      generic: true
  
  # caption
  - pymdownx.blocks.caption

  # format
  - pymdownx.tilde

  # icon
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/preisthe
      name: My Github Page

plugins:
  - git-revision-date-localized:
      enable_creation_date: true